apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: comsumetd-app
  name: consumetd
  namespace: default

spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: comsumetd-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: comsumetd-app
    spec:
      containers:
      - image: gcr.io/fid-sql/consume:td
        imagePullPolicy: Always
        name: consumetd
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
