apiVersion: v1
kind: Service
metadata:
  name: ftptd
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: port-1
    port: 18021
    protocol: TCP
    targetPort: 18021
  - name: port-2
    port: 18022
    protocol: TCP
    targetPort: 18022
  - name: port-3
    port: 18101
    protocol: TCP
    targetPort: 18101
  - name: port-4
    port: 18102
    protocol: TCP
    targetPort: 18102
  - name: port-5
    port: 18103
    protocol: TCP
    targetPort: 18103
  - name: port-6
    port: 18104
    protocol: TCP
    targetPort: 18104
  selector:
    app: ftptd
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer
